[gateway]
gateway ansible_host=3.7.218.43 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/alchemyst-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[inference]
inference ansible_host=10.0.1.214 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/alchemyst-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/alchemyst-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@3.7.218.43"'

[inference:vars]
gateway_ip=10.0.0.49
